# Generated by Django 5.2.7 on 2025-11-26 17:01

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_start_time', models.TimeField(default=datetime.time(10, 0))),
                ('work_end_time', models.TimeField(default=datetime.time(16, 0))),
                ('lunch_start_time', models.TimeField(default=datetime.time(12, 0))),
                ('lunch_end_time', models.TimeField(default=datetime.time(14, 0))),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
