# Generated by Django 5.2.7 on 2026-03-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
