# Generated by Django 5.2.7 on 2025-10-15 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_to_start_working', models.TimeField(default=datetime.time(10, 0))),
                ('time_to_finish_working', models.TimeField(default=datetime.time(16, 0))),
            ],
        ),
    ]
