# Generated by Django 5.2.7 on 2025-10-24 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barber',
            old_name='time_to_finish_working',
            new_name='work_end_time',
        ),
        migrations.RenameField(
            model_name='barber',
            old_name='time_to_start_working',
            new_name='work_start_time',
        ),
        migrations.AddField(
            model_name='barber',
            name='lunch_end_time',
            field=models.TimeField(default=datetime.time(14, 0)),
        ),
        migrations.AddField(
            model_name='barber',
            name='lunch_start_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
