# Generated by Django 5.2.7 on 2025-12-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_barber', True), ('is_customer', False)), models.Q(('is_barber', False), ('is_customer', True)), _connector='OR'), name='user_must_have_exactly_one_role'),
        ),
    ]
