# Generated by Django 5.2.7 on 2026-02-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_user_user_must_have_exactly_one_role'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='user_must_have_exactly_one_role',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_barber', True), ('is_customer', False)), models.Q(('is_barber', False), ('is_customer', True)), models.Q(('is_barber', False), ('is_customer', False), ('is_staff', True)), _connector='OR'), name='user_must_have_exactly_one_role'),
        ),
    ]
