# Generated by Django 5.2.7 on 2025-10-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment_start_date', models.DateField()),
                ('appointment_start_time', models.CharField(max_length=5)),
            ],
        ),
    ]
