# Generated by Django 5.2.7 on 2025-10-15 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('barbers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbers.barber'),
        ),
    ]
