# Generated by Django 5.2.7 on 2025-10-15 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('barber', 'appointment_start_date', 'appointment_start_time')},
        ),
    ]
