# Generated by Django 5.2.7 on 2025-10-16 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_initial'),
        ('barbers', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_start_date',
            new_name='appointment_date',
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('barber', 'appointment_date', 'appointment_start_time')},
        ),
    ]
