# Generated by Django 5.2.7 on 2026-03-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_service'),
        ('barbers', '0001_initial'),
        ('catalog', '0002_alter_service_name'),
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('barber', 'appointment_date', 'appointment_start_time'), name='unique_barber_appointment_slot'),
        ),
    ]
